server.port: 8002

spring:
  application.name: comment
  #autoconfigure:  #if only using redis, need to disable this when using JPA
  #  exclude:
  #    - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

  zipkin:
    sender.type: web
    base-url: http://192.168.56.105:9411
    service.name: comment
  sleuth.sampler.probability: 1

  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/mytest
    username: postgres
    password: Admin+86
    driver-class-name: org.postgresql.Driver
  #com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect

