server.port: 8765

spring:
  cloud:
    sentinel:
      transport:
        port: 18001
        dashboard: 192.168.56.105:8858

feign:
  sentinel:
    enabled: true

spring.application.name: service-feign