spring.config.import: configserver:http://localhost:18888/

spring.application.name: gateway
spring:
  cloud:
    config:
      uri: http://localhost:18888/
      failFast: true
      retry:
        initialInterval: 3000
        multiplier: 1.3
        maxInterval: 10000
        maxAttempts: 20
      profiles.active: default
