spring:
  application.name: product
  cloud.config:
    uri: http://localhost:18888/
    failFast: true
    retry:
        initialInterval: 3000
        multiplier: 1.3
        maxInterval: 10000
        maxAttempts: 20
  profiles.active: default

#add optional will make the app start with default configuration if remote configuration is not available
spring.config.import: configserver:http://localhost:18888/